---
- name: Copy stu-home desktop
  copy:
    src: mint-stu-home.desktop
    dest: '{{ item.homedir }}/Desktop'
    owner: '{{ item.uid }}'
    group: '{{ item.gid }}'
    mode: "0750"
  with_items: "{{ real_users }}"
- name: Remove Timeshift warning
  dconf:
    key: "/com/linuxmint/updates/warn-about-timeshift"
    value: "false"
    state: present
  become: yes
  become_user: "{{ item.user }}"
  loop: "{{ real_users }}"
- name: Remove mintupdate welcome page
  dconf:
    key: "/com/linuxmint/updates/show-welcome-page"
    value: "false"
    state: present
  become: yes
  become_user: "{{ item.user }}"
  loop: "{{ real_users }}"
