---
# tasks file for vscode
- name: Add Microsoft key
  ansible.builtin.apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
    state: present
- name: Install VSCode Repository file
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    state: present
    filename: vscode
- name: Install VSCode
  ansible.builtin.apt:
    name: 'code'
    state: latest
- name: Install Java pack plugin
  ansible.builtin.command:
    cmd: /usr/bin/code --install-extension vscjava.vscode-java-pack
  args:
    creates: '{{ item.homedir }}/.vscode/extensions/vscjava.vscode-java-pack*'
  become: yes
  become_user: "{{ item.user }}"
  loop: "{{ real_users }}"
- name: Install checkstyle plugin
  ansible.builtin.command:
    cmd: /usr/bin/code --install-extension shengchen.vscode-checkstyle
  args:
    creates: '{{ item.homedir }}/.vscode/extensions/shengchen.vscode-checkstyle*'
  become: yes
  become_user: "{{ item.user }}"
  loop: "{{ real_users }}"
