---
# tasks file for adv-prog-pkgs
- name: Install advanced language packages
  ansible.builtin.apt:
    name: '{{ adv_prog_pkgs_adv_lang }}'
    state: latest

- name: Install source control packages
  ansible.builtin.apt:
    name: '{{ adv_prog_pkgs_source_control }}'
    state: latest

- name: Install code editor packages
  ansible.builtin.apt:
    name: '{{ adv_prog_pkgs_code_editor }}'
    state: latest
