---
# tasks file for filezilla

- name: Install Filezilla package
  ansible.builtin.apt:
    name: filezilla
    state: latest
- name: Create Filezilla configuration directory
  ansible.builtin.file:
    path: "{{ item.homedir }}/{{ filezilla_config_dir }}"
    state: directory
    owner: '{{ item.uid }}'
    group: '{{ item.gid }}'
    mode: "0750"
  loop: "{{ real_users }}"
- name: Copy template default Filezilla configuration
  ansible.builtin.template:
    src: fzdefaults.xml.j2
    dest: "{{ item.homedir }}/{{ filezilla_config_dir }}/fzdefaults.xml"
    owner: '{{ item.uid }}'
    group: '{{ item.gid }}'
    mode: "0640"
  loop: "{{ real_users }}"
- name: Attempt to copy Filezilla filters
  ansible.builtin.copy:
    src: filters.xml
    dest: "{{ item.homedir }}/{{ filezilla_config_dir }}/filters.xml"
    owner: "{{ item.uid }}"
    group: "{{ item.gid }}"
    mode: "0640"
    # Don't overwrite any filters the user already has
    force: no
  loop: "{{ real_users }}"
