---
# tasks file for oem

- include_tasks: vm_only_pre.yml
  when: "ansible_virtualization_role == 'guest'"
- name: Remove unused dependencies
  apt:
    autoremove: yes
    purge: yes
- name: Install dependencies
  apt:
    name: "{{ packages_to_install }}"
    state: latest
- name: Create the /usr/local/share/applications folder
  file:
    path: /usr/local/share/applications
    state: directory
    mode: 0755
    owner: root
    group: staff
- name: Create the dconf profile directory
  file:
    path: /etc/dconf/profile
    state: directory
    mode: 0755
    owner: root
- name: Copy dconf profile file
  copy:
    src: dbus-profile
    dest: /etc/dconf/profile/user
    owner: root
    group: root
    mode: 0644
- name: Create the dconf policy directory
  file:
    path: /etc/dconf/db/local.d
    state: directory
    mode: 0755
    owner: root

- include_tasks: ubuntu_only.yml
  when: "ansible_distribution == 'Ubuntu'"
- include_tasks: mint_only.yml
  when: "ansible_distribution == 'Linux Mint'"

# Some tasks should only be run when running as a guest OS.
- include_tasks: vm_only_post.yml
  when: "ansible_virtualization_role == 'guest'"
