---
# tasks file for Ubuntu

- name: Upgrade all installed packages
  apt:
    upgrade: safe
- name: Upgrade all installed snaps  # noqa no-changed-when
  command: snap refresh
- name: Purge old snaps
  shell: |
    set -o pipefail && snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
      snap remove "$snapname" --revision="$revision"
    done
  changed_when: false
- name: Copy dconf config file
  copy:
    src: csconfig-ubuntuonly
    dest: /etc/dconf/db/local.d/csconfig-ubuntuonly
    owner: root
    group: root
    mode: "0644"
  notify:
    - Update dconf database
