---
# tasks file for Ubuntu

- name: Upgrade all installed packages
  ansible.builtin.apt:
    upgrade: safe
- name: Upgrade all installed snaps  # noqa no-changed-when
  ansible.builtin.command:
    cmd: snap refresh
- name: Purge old snaps
  ansible.builtin.shell: |
    set -o pipefail
    errors=0
    changed=""
    while read snapname revision; do
      snap remove "$snapname" --revision="$revision"
      errors=$((errors + $?))
      changed="Snap removed"
    done <<< "$(snap list --all | awk '/disabled/{print $1, $3}')"
    echo $changed
    exit $errors
  args:
    executable: /bin/bash
  register: snapout
  changed_when: '"Snap removed" in snapout.stdout'
- name: Copy dconf config file
  ansible.builtin.copy:
    src: csconfig-ubuntuonly
    dest: /etc/dconf/db/local.d/csconfig-ubuntuonly
    owner: root
    group: root
    mode: "0644"
  notify:
    - Update dconf database
