---

# Tasks for the oem role to run at the beginning of playbook execution
- name: Remove unneeded stock packages
  ansible.builtin.apt:
    name: '{{ packages_to_remove }}'
    state: absent
    purge: yes
- name: Remove i386 architecture
  ansible.builtin.lineinfile:
    path: /var/lib/dpkg/arch
    state: absent
    line: 'i386'
