---

# Tasks to only be run on virtualized guest OSes at the end of playbook
# execution

- name: Copy dconf config file
  ansible.builtin.copy:
    src: csconfig-vmonly
    dest: /etc/dconf/db/local.d/csconfig-vmonly
    owner: root
    group: root
    mode: "0644"
  notify:
    - Update dconf database

- name: Set debconf grub install_devices
  ansible.builtin.debconf:
    name: grub-pc
    question: grub-pc/install_devices
    value: /dev/sda
    vtype: multiselect

- name: Set debconf grub install_devices_disks_changed
  ansible.builtin.debconf:
    name: grub-pc
    question: grub-pc/install_devices_disks_changed
    value: /dev/sda
    vtype: multiselect

# The apt database can be fairly large and make the image unnecessarily large
# so removing it before shipping allows us to ship a smaller image.
- name: Clean the apt package cache
  command:
    cmd: apt-get clean
  # This will always report as changed otherwise
  changed_when: false
  args:
    warn: no

- name: Find package lists to delete
  ansible.builtin.find:
    paths: /var/lib/apt/lists/
    file_type: file
    excludes:
      - "lock"
  register: found_package_lists
- name: Delete apt package lists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ found_package_lists['files'] }}"

# The USB 2/3 controllers are only available with the Virtualbox
# Extensions which are non-free software and available only under the Oracle
# PUEL. We should ensure we have not accidentally included them.
- name: Validate missing USB 2/3 controllers  # noqa risky-shell-pipe
  command:
    cmd: lspci
  register: lspci_output
  failed_when: "'ECHI' in lspci_output.stdout or 'xHCI' in lspci_output.stdout"
  changed_when: false

- name: Fill disk with zeros to assist with compression
  shell:
    cmd: dd if=/dev/zero of=/bigfile bs=1M; sync; rm /bigfile
  changed_when: false
