---
# tasks file for Ubuntu

- name: Set Ubuntu mirrors
  ansible.builtin.template:
    src: ubuntu.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: "0664"
  when: "ansible_architecture == 'x86_64'"
